from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, field_validator


# -------------------------------------------------
# Shared base fields
# -------------------------------------------------
class BuildingBase(BaseModel):
    name: str
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zip: Optional[str] = None
    tmk: int
    zoning: Optional[str] = None
    year_built: Optional[str] = None
    description: Optional[str] = None
    floors: Optional[int] = None
    units: Optional[int] = None


# -------------------------------------------------
# Create
# -------------------------------------------------
class BuildingCreate(BuildingBase):
    """
    Used when creating a building.
    ID is generated by Supabase.
    """
    pass


# -------------------------------------------------
# Read (Supabase → API)
# -------------------------------------------------
class BuildingRead(BuildingBase):
    id: str                  # Always exposed as string
    created_at: datetime     # RFC3339 timestamp

    # -------------------------
    # Normalize UUID → string
    # -------------------------
    @field_validator("id", mode="before")
    def normalize_id(cls, v):
        if isinstance(v, UUID):
            return str(v)
        return str(v)

    # -------------------------
    # Fix timestamps ending in Z
    # -------------------------
    @field_validator("created_at", mode="before")
    def normalize_created_at(cls, v):
        if isinstance(v, str):
            v = v.replace("Z", "+00:00")
        return v


# -------------------------------------------------
# Update
# -------------------------------------------------
class BuildingUpdate(BaseModel):
    name: str
    address: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zip: Optional[str] = None
    tmk: int
    zoning: Optional[str] = None
    year_built: Optional[str] = None
    description: Optional[str] = None
    floors: Optional[int] = None
    units: Optional[int] = None
