# models/document.py

from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, validator


# ======================================================
# Helpers to normalize UUIDs and timestamps
# ======================================================

def _parse_uuid(value):
    if not value:
        return None
    if isinstance(value, UUID):
        return value
    try:
        return UUID(str(value))
    except Exception:
        return None


def _parse_timestamp(value):
    if isinstance(value, str) and value.endswith("Z"):
        return value.replace("Z", "+00:00")
    return value


# ======================================================
# BASE MODEL (shared)
# ======================================================

class DocumentBase(BaseModel):
    event_id: Optional[UUID] = None          # FK → events.id
    building_id: Optional[UUID] = None       # FK → buildings.id
    s3_key: str                               # S3 path used in download
    filename: str                             # Uploaded filename
    content_type: Optional[str] = None
    size_bytes: Optional[int] = None

    # --- validators ---------------------------------------------------------

    @validator("event_id", pre=True)
    def validate_event_id(cls, v):
        return _parse_uuid(v)

    @validator("building_id", pre=True)
    def validate_building_id(cls, v):
        return _parse_uuid(v)


# ======================================================
# CREATE
# ======================================================

class DocumentCreate(DocumentBase):
    """
    For incoming upload metadata BEFORE writing to Supabase.
    All timestamps & id are generated by the backend.
    """
    pass


# ======================================================
# UPDATE (PATCH)
# ======================================================

class DocumentUpdate(BaseModel):
    event_id: Optional[UUID] = None
    building_id: Optional[UUID] = None
    s3_key: Optional[str] = None
    filename: Optional[str] = None
    content_type: Optional[str] = None
    size_bytes: Optional[int] = None

    @validator("event_id", pre=True)
    def validate_event_id(cls, v):
        return _parse_uuid(v)

    @validator("building_id", pre=True)
    def validate_building_id(cls, v):
        return _parse_uuid(v)


# ======================================================
# READ (Supabase → API response)
# ======================================================

class DocumentRead(DocumentBase):
    id: str                                   # Supabase UUID (string)
    created_at: Optional[datetime] = None     # inserted timestamp

    @validator("created_at", pre=True)
    def parse_created_at(cls, v):
        return _parse_timestamp(v)
