from datetime import datetime
from typing import Optional
from uuid import UUID
from pydantic import BaseModel, field_validator


# -------------------------------------------------
# Shared base fields
# -------------------------------------------------
class UnitBase(BaseModel):
    building_id: str
    unit_number: str
    floor: Optional[str] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[int] = None
    square_feet: Optional[int] = None
    owner_name: Optional[str] = None
    parcel_number: Optional[str] = None

    @field_validator("building_id", mode="before")
    def normalize_building_id(cls, v):
        if not v:
            return None
        if isinstance(v, UUID):
            return str(v)
        return str(v)


# -------------------------------------------------
# Create
# -------------------------------------------------
class UnitCreate(UnitBase):
    """
    Used when creating a unit.
    ID is generated by Supabase.
    """
    pass


# -------------------------------------------------
# Update (all fields optional)
# -------------------------------------------------
class UnitUpdate(BaseModel):
    building_id: Optional[str] = None
    unit_number: Optional[str] = None
    floor: Optional[str] = None
    bedrooms: Optional[int] = None
    bathrooms: Optional[int] = None
    square_feet: Optional[int] = None
    owner_name: Optional[str] = None
    parcel_number: Optional[str] = None

    @field_validator("building_id", mode="before")
    def normalize_building_id(cls, v):
        if not v:
            return None
        if isinstance(v, UUID):
            return str(v)
        return str(v)


# -------------------------------------------------
# Read (Supabase → API)
# -------------------------------------------------
class UnitRead(UnitBase):
    id: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    @field_validator("id", mode="before")
    def normalize_id(cls, v):
        if isinstance(v, UUID):
            return str(v)
        return str(v)

    @field_validator("created_at", "updated_at", mode="before")
    def normalize_timestamps(cls, v):
        if isinstance(v, str) and v.endswith("Z"):
            return v.replace("Z", "+00:00")
        return v

